name: DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build DVWA image from Dockerfile
        run: docker build -t dvwa:latest .

  sca:
    name: Dependency Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit --format json --output sca-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: sca-report.json

  sast:
    name: Static Code Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          docker run --rm -v ${{ github.workspace }}:/src returntocorp/semgrep semgrep --config=auto --json > semgrep-output.json
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-output.json

  secrets:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run GitLeaks
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo zricethezav/gitleaks detect --source=/repo --report-format=json --report-path=/repo/gitleaks-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

  dast:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run DVWA container
        run: |
          docker build -t dvwa:latest .
          docker network create zapnet
          docker run -d --rm --name dvwa --network zapnet -p 3000:80 dvwa:latest
          echo "Waiting for DVWA to be available..."
          until curl -s http://localhost:3000 > /dev/null; do
            echo "Still waiting for DVWA..."
            sleep 5
          done

      - name: Create zap-output directory
        run: mkdir -p zap-output

      - name: Run ZAP Full Scan
        run: |
          docker run --rm \
            --network zapnet \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            kondukto/zap2docker-stable zap-full-scan.py \
            -t http://dvwa:80 \
            -J /zap/wrk/zap-cli-output.json \
            -r /zap/wrk/zap-report.html || true

      - uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/

  trivy:
    name: Docker Image Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan Docker image with Trivy
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image --exit-code 1 --severity HIGH,CRITICAL --format table dvwa:latest > trivy-report.txt || true
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  release:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [build, trivy]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag dvwa:latest ${{ secrets.DOCKERHUB_USERNAME }}/dvwa:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dvwa:latest
